secret: kittens

http:
  port: 8001

https:
  port: 8002
  key: key.pem
  cert: cert.pem

db:
  username: ''
  password: ''
  host: localhost
  port: 27017

reload:
  port: 6001
  proxy:
    host: localhost
    port: 8001